INFO:app:Database tables created successfully
INFO:routes.oauth_routes:OAuth redirect URI: https://55ab1b06-006d-47ec-9b73-b827f4e0f641-00-1fje9legmrd1y.riker.replit.dev/oauth/epic-callback
INFO:routes.oauth_routes:Epic client ID: e57377e2-dfd5-4675-9659-58c33aa67b3f
INFO:routes.oauth_routes:Epic auth URL: https://fhir.epic.com/interconnect-fhir-oauth/oauth2/authorize
INFO:emr.fhir_client:Epic OAuth Parameters:
INFO:emr.fhir_client:  response_type: code
INFO:emr.fhir_client:  client_id: e57377e2-dfd5-4675-9659-58c33aa67b3f
INFO:emr.fhir_client:  redirect_uri: https://55ab1b06-006d-47ec-9b73-b827f4e0f641-00-1fje9legmrd1y.riker.replit.dev/oauth/epic-callback
INFO:emr.fhir_client:  scope: openid fhirUser patient/Patient.read patient/Condition.read patient/Observation.read patient/DocumentReference.read patient/Encounter.read user/Patient.read user/Condition.read user/Observation.read user/DocumentReference.read user/Encounter.read
INFO:emr.fhir_client:  aud: https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4/
INFO:emr.fhir_client:  state: 7kjk7N2AIC_7-6YYCRdEYD3Qy2FtsW66hVm_Umo3VZw
INFO:emr.fhir_client:Generated Epic authorization URL: https://fhir.epic.com/interconnect-fhir-oauth/oauth2/authorize?response_type=code&client_id=e57377e2-dfd5-4675-9659-58c33aa67b3f&redirect_uri=https%3A%2F%2F55ab1b06-006d-47ec-9b73-b827f4e0f641-00-1fje9legmrd1y.riker.replit.dev%2Foauth%2Fepic-callback&scope=openid+fhirUser+patient%2FPatient.read+patient%2FCondition.read+patient%2FObservation.read+patient%2FDocumentReference.read+patient%2FEncounter.read+user%2FPatient.read+user%2FCondition.read+user%2FObservation.read+user%2FDocumentReference.read+user%2FEncounter.read&aud=https%3A%2F%2Ffhir.epic.com%2Finterconnect-fhir-oauth%2Fapi%2FFHIR%2FR4%2F&state=7kjk7N2AIC_7-6YYCRdEYD3Qy2FtsW66hVm_Umo3VZw
INFO:routes.oauth_routes:Starting Epic OAuth flow for organization 1
INFO:routes.oauth_routes:=== Epic OAuth Callback Debug ===
INFO:routes.oauth_routes:Request URL: https://55ab1b06-006d-47ec-9b73-b827f4e0f641-00-1fje9legmrd1y.riker.replit.dev/oauth/epic-callback?code=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1cm46b2lkOjEuMi44NDAuMTE0MzUwLjEuMTMuMC4xLjcuMy42ODg4ODQuMTAwIiwiY2xpZW50X2lkIjoiZTU3Mzc3ZTItZGZkNS00Njc1LTk2NTktNThjMzNhYTY3YjNmIiwiZXBpYy5lY2kiOiJ1cm46ZXBpYzpPcGVuLkVwaWMtY3VycmVudCIsImVwaWMubWV0YWRhdGEiOiIweEIyalJMbl9UUFlqZzl1NTE1OVpXUlYxSHljcWhpakVZcnRyalRobW1PRlNDZDJsU2pUVmk1Tjd3N08wdkRUdHdrajZOV3NxZ0pjMEk2eUhLc0l6MkhwUFdtdnAteVpGQUlzNmhyejZDQWR5RmJZbjdtRnlidDZyNnZQYmRQciIsImVwaWMudG9rZW50eXBlIjoiY29kZSIsImV4cCI6MTc1NjQ4ODgyMywiaWF0IjoxNzU2NDg4NTIzLCJpc3MiOiJ1cm46b2lkOjEuMi44NDAuMTE0MzUwLjEuMTMuMC4xLjcuMy42ODg4ODQuMTAwIiwianRpIjoiYTUwZWVkMWMtNTkzMi00MjlhLWEwMDktZWMwMTQwODBlNTBmIiwibmJmIjoxNzU2NDg4NTIzLCJzdWIiOiJlNmF3Ni1SSnVLTzJtYnFqbGVLdmdWUTMifQ.Jtc9cLz25En5navqrVDMHRqtYlUnZLBFT6lGbZtPjKZHLyA8kzKiIF-U1uoY6y-pFxnzCCuYsa2E1MkyDY3lIK2IH4d_utOBRNND-XbfK-qQLrNXL_1G45eSzcaYImMd4FXZTaTQdvjaQBEYDXOXbNkk_mrlwnBhpuoXjoU60epK2qb2kTPdyuPMJXnvVJFhONkZy6bOCBSrBcpTTqxLUUix_B6mLLdFU6MiM0xkhbL7K0jfDgTRqmmc--NfQ3Avj76R2nY1mJ1hSr2At7uyqEUNb_npkjZUS0xnp3WZ-f8orgf6oSgdQAmry85A2nuMCaS2V2sJkz2oKO3LW2QZVg&state=7kjk7N2AIC_7-6YYCRdEYD3Qy2FtsW66hVm_Umo3VZw
INFO:routes.oauth_routes:Request method: GET
INFO:routes.oauth_routes:Request headers: {'Host': '55ab1b06-006d-47ec-9b73-b827f4e0f641-00-1fje9legmrd1y.riker.replit.dev', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Replit/1.0.14 Chrome/124.0.6367.119 Electron/30.0.3 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-US', 'Cookie': 'session=.eJw1jsFKAzEQht9lz1Yyk00m01upCl4ERSv1siSTCa1lbdlNERHf3SgKc_mH_5v5PruhTDrvumWdznrRDfvcLTuQbJ0WtslYCdGU5LMQ-AIE6CIxeAklsjXYZ-eyNQygyD1gjK6w2kyJMRo0uWc2kKhPUijE4LIDEwxGT5KI-4iFKBOYiEmEC_1865rIedbpz6ZFmacy1ONB39rCS1KFImQoSRO1NmblIAoeFUFNjklF-sbpaS9DPNfdUPejzjWOp3YADbqFCQvkR6AlhjaXgdiy_UeOv0zrV219Orwe6A5Xt-uBFn67XT_k6-2Vvf_Amzo_e7_bjMPTeLSbl_fu6xvm_GPM.aLHjPA.BQsLmY8E6RMLNNsHl0BKlty5rTw', 'Referer': 'https://fhir.epic.com/', 'Sec-Fetch-Dest': 'document', 'Sec-Fetch-Mode': 'navigate', 'Sec-Fetch-Site': 'cross-site', 'Sec-Fetch-User': '?1', 'Upgrade-Insecure-Requests': '1', 'X-Forwarded-For': '69.207.59.155, 10.81.6.170', 'X-Forwarded-Proto': 'https', 'X-Replit-User-Bio': '', 'X-Replit-User-Id': '', 'X-Replit-User-Name': '', 'X-Replit-User-Profile-Image': '', 'X-Replit-User-Roles': '', 'X-Replit-User-Teams': '', 'X-Replit-User-Url': ''}
INFO:routes.oauth_routes:Query parameters received:
INFO:routes.oauth_routes:  - code: <present>
INFO:routes.oauth_routes:  - state: <present>
INFO:routes.oauth_routes:  - error: None
INFO:routes.oauth_routes:  - error_description: None
INFO:routes.oauth_routes:  - all query args: {'code': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1cm46b2lkOjEuMi44NDAuMTE0MzUwLjEuMTMuMC4xLjcuMy42ODg4ODQuMTAwIiwiY2xpZW50X2lkIjoiZTU3Mzc3ZTItZGZkNS00Njc1LTk2NTktNThjMzNhYTY3YjNmIiwiZXBpYy5lY2kiOiJ1cm46ZXBpYzpPcGVuLkVwaWMtY3VycmVudCIsImVwaWMubWV0YWRhdGEiOiIweEIyalJMbl9UUFlqZzl1NTE1OVpXUlYxSHljcWhpakVZcnRyalRobW1PRlNDZDJsU2pUVmk1Tjd3N08wdkRUdHdrajZOV3NxZ0pjMEk2eUhLc0l6MkhwUFdtdnAteVpGQUlzNmhyejZDQWR5RmJZbjdtRnlidDZyNnZQYmRQciIsImVwaWMudG9rZW50eXBlIjoiY29kZSIsImV4cCI6MTc1NjQ4ODgyMywiaWF0IjoxNzU2NDg4NTIzLCJpc3MiOiJ1cm46b2lkOjEuMi44NDAuMTE0MzUwLjEuMTMuMC4xLjcuMy42ODg4ODQuMTAwIiwianRpIjoiYTUwZWVkMWMtNTkzMi00MjlhLWEwMDktZWMwMTQwODBlNTBmIiwibmJmIjoxNzU2NDg4NTIzLCJzdWIiOiJlNmF3Ni1SSnVLTzJtYnFqbGVLdmdWUTMifQ.Jtc9cLz25En5navqrVDMHRqtYlUnZLBFT6lGbZtPjKZHLyA8kzKiIF-U1uoY6y-pFxnzCCuYsa2E1MkyDY3lIK2IH4d_utOBRNND-XbfK-qQLrNXL_1G45eSzcaYImMd4FXZTaTQdvjaQBEYDXOXbNkk_mrlwnBhpuoXjoU60epK2qb2kTPdyuPMJXnvVJFhONkZy6bOCBSrBcpTTqxLUUix_B6mLLdFU6MiM0xkhbL7K0jfDgTRqmmc--NfQ3Avj76R2nY1mJ1hSr2At7uyqEUNb_npkjZUS0xnp3WZ-f8orgf6oSgdQAmry85A2nuMCaS2V2sJkz2oKO3LW2QZVg', 'state': '7kjk7N2AIC_7-6YYCRdEYD3Qy2FtsW66hVm_Umo3VZw'}
INFO:routes.oauth_routes:Session state: 7kjk7N2AIC_7-6YYCRdEYD3Qy2FtsW66hVm_Umo3VZw
INFO:routes.oauth_routes:Session user: True
INFO:routes.oauth_routes:================================
INFO:routes.oauth_routes:Token exchange - redirect URI: https://55ab1b06-006d-47ec-9b73-b827f4e0f641-00-1fje9legmrd1y.riker.replit.dev/oauth/epic-callback
INFO:routes.oauth_routes:Token exchange - client ID: e57377e2-dfd5-4675-9659-58c33aa67b3f
INFO:routes.oauth_routes:Token exchange - token URL: https://fhir.epic.com/interconnect-fhir-oauth/oauth2/token
INFO:emr.fhir_client:Token exchange request:
INFO:emr.fhir_client:  - URL: https://fhir.epic.com/interconnect-fhir-oauth/oauth2/token
INFO:emr.fhir_client:  - client_id: e57377e2-dfd5-4675-9659-58c33aa67b3f
INFO:emr.fhir_client:  - redirect_uri: https://55ab1b06-006d-47ec-9b73-b827f4e0f641-00-1fje9legmrd1y.riker.replit.dev/oauth/epic-callback
INFO:emr.fhir_client:  - grant_type: authorization_code
INFO:emr.fhir_client:  - code: <present>
INFO:emr.fhir_client:Token exchange response:
INFO:emr.fhir_client:  - status_code: 200
INFO:emr.fhir_client:  - headers: {'Cache-Control': 'no-cache, no-store,no-store', 'Pragma': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'Expires': '-1', 'Set-Cookie': 'ASP.NET_SessionId=gss4tddtzwz151aiqsrb2q5a; path=/Interconnect-fhir-oauth; secure; HttpOnly; SameSite=Lax, EpicPersistenceCookie=!LikWQXX1AxdE2Xdc5iqg712Vrh0WW92vRN/0bIjzsBfhPIQJ4KYVztVP+zkkIYzU5dmYl+65E9EAK3I=; path=/; Httponly; Secure', 'ServerMetrics': '{"BlockReads":18,"BlockWrites":5,"BlocksAllocated":0,"DBTime":30,"DatabaseCPUTime":29,"ECFNetworkTime":2,"ECFRequestCount":1,"ECFRequestTime":32,"GREF":2389,"JournalEntries":11,"LockWait":0.048,"LocksFailed":0,"LocksGranted":0,"MCommands":45142,"MemoryDifference":0,"NetworkCacheMisses":0,"NetworkUpdates":0,"WorkflowEventBlockReads":18,"WorkflowEventDBTime":30,"WorkflowEventECFNetworkTime":1,"WorkflowEventECFRequestCount":1,"WorkflowEventGREF":2389}', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Frame-Options': 'sameorigin', 'Access-Control-Allow-Headers': 'origin, authorization, accept, content-type, x-requested-with, prefer, Epic-User-ID, Epic-User-IDType, Epic-Client-ID, soapaction, Epic-MyChartUser-ID, Epic-MyChartUser-IDType', 'Access-Control-Allow-Methods': 'GET, HEAD, POST, PUT, DELETE, TRACE, OPTIONS', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true', 'Date': 'Fri, 29 Aug 2025 17:28:43 GMT', 'Content-Length': '3386'}
INFO:emr.fhir_client:Successfully exchanged authorization code for Epic access token
ERROR:routes.oauth_routes:Error handling Epic OAuth callback: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(255)

[SQL: UPDATE epic_credentials SET access_token=%(access_token)s, refresh_token=%(refresh_token)s, token_expires_at=%(token_expires_at)s, token_scope=%(token_scope)s, updated_at=%(updated_at)s WHERE epic_credentials.id = %(epic_credentials_id)s]
[parameters: {'access_token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1cm46b2lkOjEuMi44NDAuMTE0MzUwLjEuMTMuMC4xLjcuMy42ODg4ODQuMTAwIiwiY2xpZW50X2lkIjoiZTU3Mzc3ZTItZGZkNS00 ... (754 characters truncated) ... 2Jvt7LasJn6CCbn0LlnXH3rK66xBDHqFaZIlLPy_04ksJKqRWV6Xtk5qkpQ61R0j7tS6xQN74CBWGYlv_iOZLj-vpY3WTakQq3ntqIkvM-azKk2mVJzOozDWPsmoZzzOhca9yT5Sk2TAGld4lwaiA', 'refresh_token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1cm46b2lkOjEuMi44NDAuMTE0MzUwLjEuMTMuMC4xLjcuMy42ODg4ODQuMTAwIiwiY2xpZW50X2lkIjoiZTU3Mzc3ZTItZGZkNS00 ... (733 characters truncated) ... fTCrP3mTpndcukle_LT4cbygj3jQhnZbmNFO_Kwjfv7iETUw3Ce7vlu6U4PDhzDsi1jDqWlyy3f2ul8YuABKqaZc-bQyRX2N20kjI7jUuii3CNkGt7gSBzrXm8ch3v6DeIrXrNo5bLP15LrXTBwVg', 'token_expires_at': datetime.datetime(2025, 8, 29, 18, 28, 43, 471901), 'token_scope': 'user/AllergyIntolerance.read user/Binary.read user/CarePlan.read user/Condition.read user/DiagnosticReport.read user/DocumentReference.read user/Encounter.read user/Goal.read user/List.read user/Observation.read user/Patient.read user/Procedure.read fhirUser offline_access openid', 'updated_at': datetime.datetime(2025, 8, 29, 17, 28, 43, 494033), 'epic_credentials_id': 1}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1961, in _exec_single_context
    self.dialect.do_execute(
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 944, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(255)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/workspace/routes/oauth_routes.py", line 393, in epic_callback
    db.session.commit()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/scoping.py", line 599, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4345, in flush
    self._flush(objects)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4480, in _flush
    with util.safe_reraise():
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4441, in _flush
    flush_context.execute()
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 85, in save_obj
    _emit_update_statements(
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 912, in _emit_update_statements
    c = connection.execute(
        ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
           ^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 526, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1840, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1980, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2349, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1961, in _exec_single_context
    self.dialect.do_execute(
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 944, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(255)

[SQL: UPDATE epic_credentials SET access_token=%(access_token)s, refresh_token=%(refresh_token)s, token_expires_at=%(token_expires_at)s, token_scope=%(token_scope)s, updated_at=%(updated_at)s WHERE epic_credentials.id = %(epic_credentials_id)s]
[parameters: {'access_token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1cm46b2lkOjEuMi44NDAuMTE0MzUwLjEuMTMuMC4xLjcuMy42ODg4ODQuMTAwIiwiY2xpZW50X2lkIjoiZTU3Mzc3ZTItZGZkNS00 ... (754 characters truncated) ... 2Jvt7LasJn6CCbn0LlnXH3rK66xBDHqFaZIlLPy_04ksJKqRWV6Xtk5qkpQ61R0j7tS6xQN74CBWGYlv_iOZLj-vpY3WTakQq3ntqIkvM-azKk2mVJzOozDWPsmoZzzOhca9yT5Sk2TAGld4lwaiA', 'refresh_token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1cm46b2lkOjEuMi44NDAuMTE0MzUwLjEuMTMuMC4xLjcuMy42ODg4ODQuMTAwIiwiY2xpZW50X2lkIjoiZTU3Mzc3ZTItZGZkNS00 ... (733 characters truncated) ... fTCrP3mTpndcukle_LT4cbygj3jQhnZbmNFO_Kwjfv7iETUw3Ce7vlu6U4PDhzDsi1jDqWlyy3f2ul8YuABKqaZc-bQyRX2N20kjI7jUuii3CNkGt7gSBzrXm8ch3v6DeIrXrNo5bLP15LrXTBwVg', 'token_expires_at': datetime.datetime(2025, 8, 29, 18, 28, 43, 471901), 'token_scope': 'user/AllergyIntolerance.read user/Binary.read user/CarePlan.read user/Condition.read user/DiagnosticReport.read user/DocumentReference.read user/Encounter.read user/Goal.read user/List.read user/Observation.read user/Patient.read user/Procedure.read fhirUser offline_access openid', 'updated_at': datetime.datetime(2025, 8, 29, 17, 28, 43, 494033), 'epic_credentials_id': 1}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)